path:
  dir_all_word_files: /home/stapan/GIT/kn7072/ANKI/WORDS
  words_for_learn: /home/stapan/GIT/kn7072/ANKI/TelegramBot/WORDS_FOR_LEARN.txt
  words_for_learn_clean: /home/stapan/GIT/kn7072/ANKI/TelegramBot/WORDS_FOR_LEARN_CLEAN.txt
  path_to_all_words: /home/stapan/GIT/kn7072/ANKI/TelegramBot/ALL_WORDS.txt
  path_to_sentence: /home/stapan/GIT/kn7072/ANKI/Предложения.txt
  file_to_add_sentence: ./ADD_SENTENCE.txt
  count_sentence_for_word: 2